# Generated by Django 4.2 on 2023-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_mins_post_ratings_post_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
