# Generated by Django 4.2 on 2023-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_bg_image_link_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genere',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
